# Generated by Django 4.2.1 on 2023-05-18 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_storge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
    ]
