# Generated by Django 4.2.1 on 2023-05-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_storge', '0002_mytext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shingle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField()),
                ('as_like', models.CharField(max_length=250)),
                ('text_file1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_text_file', to='file_storge.storge_file')),
                ('text_file2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_text_file', to='file_storge.storge_file')),
            ],
        ),
    ]
