# Generated by Django 4.2.1 on 2023-05-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shingle', '0002_shingle_text_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_main', models.TextField(unique=True)),
            ],
        ),
    ]
